### ISSUE TITLE
Add multiple selection

### ISSUE THREAD

**Issue by licaon-kter** [M66B/open-source-email#10]
Eg. Long press on message, marks message, top bar appears with Delete/Archive/Star/Unread/etc, but then you can touch multiple messages to select them too

**Comment by M66B** [comment]
IMHO swipe left to trash and swipe left to archive as in #55 would be nicer and easier to use.

I see no need for batch starring as in #9 

Marking unread is an exception IMHO.

**Comment by M66B** [comment]
Multiple selection will not be added in favor to swipe action.

Multiple selection often goes wrong due to accidental touches.
