### ISSUE TITLE
Create a Unread Email and a Read Email split in Unified inbox

### ISSUE THREAD

**Issue by icecoldsipra** [M66B/open-source-email#100]
Is it feasible to provide a split to separate out all unread emails from the read emails? The unread emails can be made available at the top, while all read emails can be separated out similar to how gmail allows us to organize the mailbox. This can be limited to the Unified inbox as that's where a user is going to find the emails. Currently, both read and unread emails are sorted based on date and time received. if I leave an older email as unread, it gets left behind as I receive new emails in my mailbox. Adding this option can really help organize my mailbox better.

**Comment by M66B** [comment]
Unread messages are clearly marked, so you can easily scroll to discover all unread emails.

The goal is to keep this app as simple as possible and to have little or no options. This is also to reduce the number of support questions.

Summarize, I see no good reason to add this, sorry. Thanks for the suggestion anyway.

**Comment by M66B** [comment]
Maybe I will add is as a sort on read in #101
