### ISSUE TITLE
Sort on ...

### ISSUE THREAD

**Issue by icecoldsipra** [M66B/open-source-email#101]
It would be nice if an option to sort emails either by sender or by starred emails is provided. Currently I do not see such an option.

**Comment by M66B** [comment]
Sort on:

* sender
* starred
* unread

**Comment by icecoldsipra** [comment]
Sounds good!! Looking forward to an even more awesome FairEmail app.

**Comment by M66B** [comment]
The next release will have sort on time, unread, starred.
Fore anything else, you can use the search.

**Comment by icecoldsipra** [comment]
Thank you for looking into this request!
