### ISSUE TITLE
[UI Enhancement] Move the star from the contacts-email nearer to subject and body

### ISSUE THREAD

**Issue by sas-3** [M66B/open-source-email#102]
Move the star from the contacts-email nearer to subject and body of the mail (see screenshot -> https://1drv.ms/u/s!AsBtUmW9CbVC2GcHuKSs3c8jmShA); that way there is a bit more space for a bigger contact-pic. For me, it would be a little more logical (to star the message rather than the contact; in my eyes at least 

![screenshot_fairemail](https://user-images.githubusercontent.com/38133484/45264111-9329ef00-b437-11e8-91cf-9495fe45e5ff.jpg)

**Comment by M66B** [comment]
I like to keep the items in message list and message view header similar. In the message list there are already icons at the end of the subject line and showing the star there too would be ugly. Moreover, I have no plans to increase the contacts photo size, so I am going to keep it like it is.

**Comment by sas-3** [comment]
Okay, understand. I didn't think about consitency😀
