### ISSUE TITLE
Swiping a message away (right) moves the message to trash

### ISSUE THREAD

**Issue by marsender** [M66B/open-source-email#105]
# Bug report
When I swip a message to the right, the message is moved to the trash (as when I swip the message to the left) and not archived. I tried to create a "All" folder but It doesn't change anything.
My mail provider is "free.fr".
Thanks

## Version
* App version: 0.36
* Android version: 8.0.0

**Comment by M66B** [comment]
You'll need to select the create all folder while configuring the account as well.

**Comment by marsender** [comment]
Oh sorry: that's absolutely fine. I've found the account option.
Thanks a lot and congratulations for this application !
