### ISSUE TITLE
In debug mode swipe icons are stretched

### ISSUE THREAD

**Issue by rancidfrog** [M66B/open-source-email#107]
As shown below, Swipe icons stretched:
![](https://i.imgur.com/LvWj18G.png)
And,
![](https://i.imgur.com/SOdVo7M.png)

Delete icon is confusing when stretched.
Options, add larger icon format or edit view to keep original icon size.

**Comment by M66B** [comment]
Isn't there an error message too? Or did you enable debug mode?

**Comment by rancidfrog** [comment]
This when Advanced | debug is checked![](https://i.imgur.com/IKvcuwQ.png),

**Comment by rancidfrog** [comment]
Also, by default show contact photos is checked/enabled, but permission request was never asked and no permissions granted for app:
![](https://i.imgur.com/pCWby0m.png)
Just curious, should app request it? When?

**Comment by M66B** [comment]
The setup screen is pretty clear about this IMHO.

**Comment by rancidfrog** [comment]
So, you have to manually select grant permission option:
![](https://i.imgur.com/uIZSM7A.png)
I was just confused as I just noticed the "Show contact photos" when I was checking for Debug mode, and it was enabled without requesting any permissions, (As some apps request automatically as soon as permission is needed).
Okay, just a little curious.

**Comment by M66B** [comment]
The option is there only for people not wanting contact photos and because it is a new feature that could have problems.
