### ISSUE TITLE
When setting up account clicking info icon in signature then back button resets everything

### ISSUE THREAD

**Issue by rancidfrog** [M66B/open-source-email#108]
When adding new account,
Clicking info button in signature,
![](https://i.imgur.com/tvJ3irH.png)
Takes you to pro features, but when you either click back button or back arrow all info inputted is reset:
![](https://i.imgur.com/zQ1qYsp.png)
Forcing you to start anew.
Slight annoyance.

**Comment by M66B** [comment]
Never overlook the obvious ... I tried several solutions, but actually this could be solved in a very simple way.

**Comment by rancidfrog** [comment]
Great.
Keep it simple. :construction_worker:
