### ISSUE TITLE
outlook: sent message gets saved in draft, outbox, and sent.

### ISSUE THREAD

**Issue by rancidfrog** [M66B/open-source-email#109]
With outlook sent message gets saved in draft and stays in outbox and stored in sent folder:
![](https://i.imgur.com/eLikpBX.png) 
All 1 messages in the 3 different folders are the same message that I sent to test.

Store sent messages is currently disabled:
![](https://i.imgur.com/IpIWaz3.png)

But I am pretty sure enabling it will only cause duplicate sent messages, as that is what happens with k9-mail

**Comment by rancidfrog** [comment]
> Draft messages are deleted before placing a message in the sent folder, so I don't see how they can stay behind.

> Moving messages from the outbox to sent reply on feedback of the provider. Deleting messages from the outbox is not an option because that could result in permanent losing the message. Moving the message to the sent folder might result in duplicates. So, there are few options here.

> I cannot reproduce this problem, so unless you describe the exact steps to reproduce this, there is little I can do. 

> It appears that I can reproduce this issue with Outlook. The cause is that Outlook overrides the set message ID. The only way to fix this is to delete messages from the outbox after sending, for which I will add an option, provided you create a new issue for this to remind me of this. It doesn't fit in this issue anymore.

**Comment by M66B** [comment]
There is no way to solve this because Outlook discards the message ID FairEmail sets, so there is no way to correlate messages in the outbox and in the sent folder.

The only option would be to delete the message in the outbox after sending, but this could result in lost messages.

I am afraid that *store sent* and having duplicate sent messages is the only reasonable 'option'. Blame Microsoft.

**Comment by rancidfrog** [comment]
Strange, indeed.
So what happens, outlook changes message id? 
Is there a way to check for that and link message ID set by fairemail to point to the new id?

**Comment by M66B** [comment]
As said, Outlook erases the info FairEmail sets, including the message ID, so there is no solution possible.

**Comment by rancidfrog** [comment]
Another thought.
Deleting might be an option, though.
Since it would be exactly the same as 'store sebt message'. The only difference being instead of moving sent message to sent folder(creating duplicates) deleting sent messages, since outlook already moves it.
So. Theoretically storing and deleting should both work the same way (as in both check for sent successful - the difference one creates a duplicate the other deletes)

**Comment by M66B** [comment]
As explained there is a risk losing messages this way.
Sent messages do not always arrive.

**Comment by rancidfrog** [comment]
But, doesn't FairEmail track the new message ID that outlook generates?

**Comment by M66B** [comment]
That is not possible.

**Comment by M66B** [comment]
If Outlook erases all info FairEmail sets, there is nothing to track. So, there is no way to related a message in the outbox (with FairEmail message ID) and in the sent folder (with Outlook ID and FairEmail message ID erased).

**Comment by rancidfrog** [comment]
Seems like outlooks complicates matters:
[stackoverflow](https://stackoverflow.com/questions/42291195/get-messageid-of-a-sent-mail-in-outlook) gives 3 options, 

- Redemption ~ http://www.dimastr.com/redemption/home.htm
- MAPI
-  EWS

> you can retrieve the MessageID aka InternetMessageId using Redemption. The other alternative is to ask the ExchangeServer using MAPI or EWS. In all cases there will be a 'server call' and it cannot be retrieve directly after sending because this property is set by Exchange Mail server.


```
Outlook Redemption works around limitations imposed by the Outlook Security Patch plus provides a number of objects and functions to work with properties and functionality not exposed through the Outlook object model.

Redemption library includes the RDO (Redemption Data Objects) family of objects that can function as a complete Outlook Object Model or CDO 1.21 replacement.

With Outlook Redemption you can

Make your code runs unaffected by the Security Patch.

Access properties not exposed by the Outlook Object Model (internet message headers, sender e-mail address and hundreds more properties)

Display Address Book.

Directly access RTF body of any Outlook item

Import MSG, MIME (EML/RFC822), vCard, iCalendar and TNEF files

Export messages to the MSG, EML, TXT, HTML, MHTML, TNEF, iCal, vTodo and vCard formats.

Access and manipulate Outlook accounts (Outlook 2002 and above, RDO library)

Create, access and manipulate MAPI profiles and accounts (Profman library, see also RDOSession.Profiles)

Access MAPI stores.

Access Outlook nicknames.

Manage Junk Mail settings

Manage categories

Directly access message attachments as strings or as arrays without saving them as files first

Use Incremental Change Synchronization (ICS) API to sync your data with Exchange folders.

Manage Exchange rules, folder Access Control Lists (ACL), etc.

Recover deleted messages and folders from Exchange mailboxes

And much, much more!

```

One solution using redemption,
> you can use Redemption and its RDOSession.GetMessageFromID method which allows to (optionally) specify the flags:

```
set YourMailItem = Application.ActiveExplorer.Selection(1) MAPI_NO_CACHE = &H0209 MAPI_BEST_ACCESS = &H0010 set Session = CreateObject("Redemption.RDOSession") Session.MAPIOBJECT = Application.Session.MAPIOBJECT set Mail = Session.GetMessageFromID(YourMailItem.EntryID, , MAPI_NO_CACHE + MAPI_BEST_ACCESS) MsgBox Mail.Fields("http://schemas.microsoft.com/mapi/proptag/0x1035001F")
```

**Comment by M66B** [comment]
That requires ActiveSync. FairEmail works with IMAP.

**Comment by rancidfrog** [comment]
https://github.com/bbottema/simple-java-mail/issues/79 ?

**Comment by M66B** [comment]
As said before, FairEmail already sets a message ID.

I understand you want to have this fixed, but only Microsoft can fix this.

**Comment by rancidfrog** [comment]
I guess.
![](https://i.imgur.com/Gnc3hw1.png)
 Too good to be true, then.

**Comment by rancidfrog** [comment]
Scouring, I might have found something useful:
https://stackoverflow.com/a/19359193
```
I had a similar problem when I used Amazon SES as my SMTP server, It over-rode my Javamail Message-ID and replaced it with its own. A short and simple solution would be to send a randomly generated UID in the reference header ( Reference header is not usually over-written by most Email service providers) :-

Something like this : email.setHeader("References", reference);where reference header is like this : reference = UUID.randomUUID().toString()+"@email.abcd.com"

For more detail on Reference header, see this : http://cr.yp.to/immhf/thread.html


```
 https://stackoverflow.com/questions/19320086/how-to-match-replied-emails-to-the-sent-invitationsjava-mail

The added reference might be in body, though:
https://stackoverflow.com/a/19380017

**Comment by M66B** [comment]
It seems the references headers is being left alone, so I will use this as a workaround.
