### ISSUE TITLE
Not all IMAP folders are shown

### ISSUE THREAD

**Issue by licaon-kter** [M66B/open-source-email#11]
_I'll add some pics later_

**Comment by M66B** [comment]
All folders are listen for me. Note that folders marked as *Noselect* by the mail server will not be imported. Please provide more details.

Relevant standard: https://tools.ietf.org/html/rfc3501

**Comment by M66B** [comment]
Please reopen this issue if this is still a problem in version 0.5 or later (not released yet).

**Comment by licaon-kter** [comment]
There were. Thanks
