### ISSUE TITLE
Can't select account for Google OAuth authentication in F-Droid version

### ISSUE THREAD

**Issue by toXel** [M66B/open-source-email#110]
Hi! Thanks for this awesome project!

I've seen the recent addition of support for Google OAuth authentication. I tried it now and it's not working. When I select my account I get the toast message `UNREGISTERED_ON_API_CONSOLE`. I researched a bit and found [this](http://stackoverflow.com/questions/40997205/ddg#41012703) SO thread.

Is there anything you can do about it?

**Comment by M66B** [comment]
I guess you are using the F-Droid version. Switch to the GitHub version and it will work.

**Comment by toXel** [comment]
Thanks for the fast answer. That totally makes sense when I think about it now :smile:. I'll try it.

**Comment by toXel** [comment]
It works. I'll close this.

**Comment by M66B** [comment]
```./android-studio/jre/bin/keytool -list -printcert -jarfile ~/eu.faircode.email_36.apk
Signer #1:

Signature:

Owner: CN=FDroid, OU=FDroid, O=fdroid.org, L=ORG, ST=ORG, C=UK
Issuer: CN=FDroid, OU=FDroid, O=fdroid.org, L=ORG, ST=ORG, C=UK
Serial number: 5f9ef2fe
Valid from: Thu Aug 30 09:18:15 UTC 2018 until: Mon Jan 15 09:18:15 UTC 2046
Certificate fingerprints:
         MD5:  65:98:8A:D1:01:1E:D1:EE:A1:29:62:C9:D7:47:1D:64
         SHA1: **77:CD:40:05:88:58:DC:3A:38:52:3E:01:C2:27:A3:9A:A0:19:F8:8B**
         SHA256: B9:D0:41:58:2A:F4:6E:E3:9B:BA:0F:2F:18:29:D9:48:AE:21:EC:F7:FF:A6:BA:12:03:85:D2:45:EB:B7:88:AE
         Signature algorithm name: SHA256withRSA
         Version: 3
```
