### ISSUE TITLE
[FR] Force different app language

### ISSUE THREAD

**Issue by Kelvino9** [M66B/open-source-email#111]
Would it be possible to force change the app language in settings?
Reason: I generally have my phone set to English, but as I'm translating FairEmail in another language I have to use my phone in that language to check how the translation turns out in each context.

I'm aware that this is not a really needed option, more a nice to have. If it is possible to launch the app through terminal in another language that would suffice for my purpose.

**Comment by M66B** [comment]
Android manages languages and although it is possible to force a language in an app (some apps do), this should not be done.

**Comment by Kelvino9** [comment]
I accept the rejection of this request, but I don't understand why it should not be done? Could you briefly elaborate?

**Comment by M66B** [comment]
The goal is to have a minimalistic email client with no options and this would require an option.

**Comment by Kelvino9** [comment]
Okay, I understand. 
> The goal is to have a minimalistic email client with no options and this would require an option.

One more thing and that's more for my personal understanding of how I should threat FairEmail.
You often describe FairEmail to be a simple mail client. Do you mean simple as in easy to use / easy on the eye or simple as in minimalistic (as you just mentioned) with very few or limited customization options. To me there is a noticeable difference, also in my perception of what to expect from an app.

**Comment by M66B** [comment]
simple = minimalistic = easy to use = less questions

**Comment by Kelvino9** [comment]
Thanks
