### ISSUE TITLE
[FR] browse online messages

### ISSUE THREAD

**Issue by CircleCode** [M66B/open-source-email#115]
it is sometimes useful to be able to browse directorie online, while not needing them to be synchronized.
For now, this application exclusively allows to read messages offline.

It can be useful to allow to browse folders even when they are not synced, and to read those online messages.

**Comment by rancidfrog** [comment]
How do we know the difference, though?

**Comment by M66B** [comment]
I am not sure what you mean, but there will be a spinner when messages are retrieved from the server.
