### ISSUE TITLE
Battery drain? 

### ISSUE THREAD

**Issue by maninthemiddle01** [M66B/open-source-email#119]
Hi, is there a Barrera drain or do I do something wrong? 
Lineage os 14.1
FairEmail Version 0.47

**Comment by M66B** [comment]
I have no battery drain.

How do you know FairEmail is draining the battery?
Do you have a stable internet connection?

**Comment by maninthemiddle01** [comment]
![screenshot_20180914-174301](https://user-images.githubusercontent.com/12028992/45565134-f4482d00-b852-11e8-8ce0-1947d9f3685a.png)

It looks like this

**Comment by M66B** [comment]
Do you have a stable internet connection?

**Comment by maninthemiddle01** [comment]
yes

**Comment by M66B** [comment]
Please send me the debug information after you have upgraded to the latest version:

https://github.com/M66B/open-source-email/releases

Between version 0.47 and 0.53 are almost 100 commits and more than 100 files changed:
https://github.com/M66B/open-source-email/compare/0.47...0.53

**Comment by M66B** [comment]
Another question: did you synchronize a lot of messages?
