### ISSUE TITLE
Sometimes when you reply a message the original message text is missing

### ISSUE THREAD

**Issue by sas-3** [M66B/open-source-email#122]
## Expected behavior
To see the original text cited under the text I am writing.

## Actual behavior
Sometimes the message text is missing and you write in an empty field.

## Steps to reproduce the problem

1. Reply to a message 
1.
1.

## Version

* App version: 0.54
* Android version: 7.1.1

**Comment by M66B** [comment]
I have never seen this happen, which will make it difficult to fix.
Can you please be more specific about how to reproduce this?
For example, was it a large message?

**Comment by sas-3** [comment]
No not particularly large. It had some signature-pictures or so something in it. Would it make sense to forward the broken message to you?
Sat Sep 15 09:37:53 GMT+02:00 2018 M66B/open-source-email <reply@reply.github.com>:
I have never seen this happen, which will make it difficult to fix.
Can you please be more specific about how to reproduce this?
For example, was it a large message?

**Comment by M66B** [comment]
Yes, please forward the message.

**Comment by sas-3** [comment]
I have forwarded it to your support address. It seems that also with forwarding the body text gets missing?
Sat Sep 15 09:52:02 GMT+02:00 2018 M66B/open-source-email <reply@reply.github.com>:
Yes, please forward the message.

**Comment by sas-3** [comment]
I am going to send the message again from my computer, when I am back home! Thx sas-3

**Comment by M66B** [comment]
Good. No hurry, I will not be able to work on FairEmail today anyway.

**Comment by M66B** [comment]
Can you please reproduce this issue and send me the debug info directly after that?

**Comment by sas-3** [comment]
Is on its way👌
Sun Sep 16 12:51:05 GMT+02:00 2018 M66B/open-source-email <reply@reply.github.com>:
Can you please reproduce this issue and send me the debug info directly after that?

**Comment by M66B** [comment]
Thanks, the debug info revealed what the problem was.

**Comment by sas-3** [comment]
Great, thx for fixing!
Sun Sep 16 13:13:45 GMT+02:00 2018 M66B/open-source-email <reply@reply.github.com>:
Thanks, the debug info revealed what the problem was.
