### ISSUE TITLE
attachment name encoding

### ISSUE THREAD

**Issue by Buxdehuda** [M66B/open-source-email#124]
# Bug report

## Expected behavior
The name of an attachment gets encoded correctly, even when it contains country-specific characters (for example: ä, ö, ü)

## Actual behavior
`=?UTF-8?Q?Fr=C3=BChjahr.pdf?=` instead of Frühjahr.pdf

`=?iso-8859-1?Q?L=F6sung.pdf?=` instead of Lösung.pdf

## Version

* App version: 0.55
* Android version: 7.0

**Comment by M66B** [comment]
The forwarded message looks good in my version of the app.
Note that FairEmail doesn't attempt to fix broken messages (wrong encoding, etc), so this problem might be caused by your provider.
