### ISSUE TITLE
[FR] notification grouping / delete from notification

### ISSUE THREAD

**Issue by TheMadRuffian** [M66B/open-source-email#126]
It would be convenient and time saving to manage less priority emails.

**Comment by M66B** [comment]
Mark as read from the notification will be in the next release.

Delete from the notification is not a good idea IMHO.

**Comment by Kelvino9** [comment]
I use mark as read, delete and reply from the pull down notification frequently with AquaMail. Especially when following Forums or Github some frequent emails can be deleted without opening. Falsely deleted emails would still be noticeable in the trash folder and clewrly visible as unread.

**Comment by Kelvino9** [comment]
Speaking of undoing. The message field that pops up when deleting a mail still says "trash" in the translation. It should fetch the translated term instead. This is the case with the German translation, but sure of this behavior in other languages

**Comment by M66B** [comment]
You can fix translations here:
https://crowdin.com/project/open-source-email

**Comment by Kelvino9** [comment]
I am fully aware of Crowdin. I am maintaining the German translation since it were made available there. I checked and every mention of "trash" has been translated some time ago.

**Comment by M66B** [comment]
That is odd because the translations are all coming from Crowdin. I will check.

**Comment by Kelvino9** [comment]
Let me know if I can assist in testing.

**Comment by M66B** [comment]
The translation seems to be okay:
https://github.com/M66B/open-source-email/blob/master/app/src/main/res/values-de/strings.xml#L151
https://github.com/M66B/open-source-email/blob/master/app/src/main/res/values-de/strings.xml#L159

Which message do you see not correctly translated and where/when?

**Comment by Kelvino9** [comment]
It is the message when you swipe a mail to delete and being offered to undo the deletion.

![image_2018-09-19_17-18_1](https://user-images.githubusercontent.com/20547677/45765163-a5c0d700-bc34-11e8-993a-66cd25f2dbfe.jpg)

**Comment by M66B** [comment]
'Trash' is how your provider names your trash folder.

**Comment by Kelvino9** [comment]
If that is the case, then it is the just the backend of my mail provider. The web frontend or a mail program or app can interpret the imap designation any way it wants and they do. In the case of interface localization FairEmail should handle the proper language. Replace the dialogue content with a static translation. Don't use the imap designation at all.
