### ISSUE TITLE
[FR] Allow hiding the notification on Android < 8.0

### ISSUE THREAD

**Issue by X-Ryl669** [M66B/open-source-email#127]
First, many thanks for you application, it solves the email issue for me.

Currently, on Android Nougat, there is the mandatory *application running* notification we can't hide (else we lose the new mail notification as well).
This is painful, and Google made is this way so you are forced to use their FCM stuff. 
I think I've a way to solve this:

1. It requires another app that:
1.1 Listen to some specific intent
1.2 Display a notification when such intents are received
1.3 Broadcast an intent when clicked, which your application would reply to resume the main activity.

On your side, this would allow the user to hide the notification (pre Android 8.0, it's for the complete application), yet receive some notification when something's happening.

**Comment by M66B** [comment]
This is not going work because the problem is that a foreground service needs to run.
See here for more on Android services:
https://developer.android.com/guide/components/services

**Comment by X-Ryl669** [comment]
When you hide the notification, the application still run! 
I had the same issue with my app, and I'm 100% sure about this.
The only issue is that your other application's notifications are not displayed either.

**Comment by M66B** [comment]
Still this is not going to happen because it will only result in many questions.
