### ISSUE TITLE
Missing .gitmodules

### ISSUE THREAD

**Issue by relan** [M66B/open-source-email#128]
Hi,

F-Droid maintainer here. We've got a problem building FairEmail: git cannot fetch `colorpicker` submodule because `.gitmodules` is missing. Please add it under the source control.

**Comment by M66B** [comment]
Done, but untested.

**Comment by licaon-kter** [comment]
@relan thanks, was looking at this too 👉👍

**Comment by relan** [comment]
Thanks.
