### ISSUE TITLE
[FR] Don't force user to type default settings

### ISSUE THREAD

**Issue by weiss** [M66B/open-source-email#130]
The IMAP/SMTP settings show default ports in the text input fields.  It would be nice if those were just used in case the user doesn't touch these fields, rather than forcing the user to re-type those port number.

Similarly, it would be nice if the IMAP folder names were pre-selected in the configuration.

**Comment by M66B** [comment]
IMAP folders will be pre-selected, if the provider sets the correct folder attributes.

**Comment by M66B** [comment]
There are no default settings for IMAP and SMTP, just a hint what it could be. Most people will use one of the profiles anyway and with #129 there is even less reason to type something. Also, it is not that adding an account or identity needs to be done daily.

**Comment by weiss** [comment]
I'll easily agree this is not a drama (for the reasons you mentioned), I just don't see a downside in using the hint if the user didn't specify a port.  In practice, that will be the port almost all providers offer.

> it is not that adding an account or identity needs to be done daily.

True, but it's something many users struggle with, so I think avoiding unnecessary UX glitches during on-boarding is desirable, even if they're small.

Whatever.  This is a nice client, thank you :-)
