### ISSUE TITLE
Connection drop after some time and never resumes.

### ISSUE THREAD

**Issue by X-Ryl669** [M66B/open-source-email#131]
Left the software running for 2 days now. It's not synchronizing the imap folder anymore.
I still have the notification saying "Synchronization..." 
I've added the debug information and I'm getting this:
```
* BYE JavaMail Exception: javax.net.ssl.SSLException: Read error: ssl=0x7F731B0480: I/O error during system call, Software caused connection abort
```

**Comment by X-Ryl669** [comment]
Stopped and restarted the software made it work again, but it's not a solution since I want push email to work unattended.

**Comment by M66B** [comment]
FairEmail will automatically reconnect after connectivity errors. In 'about' you'll find a log with details about this. If this doesn't happen, please reproduce the problem, take note of the time and send me a debug info ASAP after the problem.

When you created this issue you were asked for vital information, like version numbers. I am wondering why you didn't provide that.
