### ISSUE TITLE
Mark Unread in action menu

### ISSUE THREAD

**Issue by heinhuiz** [M66B/open-source-email#132]
Can you add Mark Unread to the action menu while reading an e-mail?
That would be more convenient, because most of the time, one decides to mark a mail unread (and deal with it later) while reading it. Now you have to go back to the folder, and find and longpress the mail from the list.

**Comment by M66B** [comment]
Duplicate of #126

**Comment by heinhuiz** [comment]
I think #126 deals with the notification. I meant the three dot action menu in the upper right corner while you are actually reading a mail.
