### ISSUE TITLE
Open links in separate browser

### ISSUE THREAD

**Issue by markwmuller** [M66B/open-source-email#133]
# Feature request

When I click a link in an email, I'd like to open that link in my browser, rather than the app's built-in browser (for me, I'd like to have it open in firefox). 

* App version: 0.62
* Android version:8.1.0

**Comment by M66B** [comment]
FairEmail opens links in [custom tabs](https://developers.chrome.com/multidevice/android/customtabs), not in its own web browser. If Firefox supports custom tabs, links will be opened in Firefox.

**Comment by markwmuller** [comment]
Thanks for the clarification. FWIW, I'd prefer to have it open my browser (or at least, an option for me to force it to do so): often I'd like to open a link (to deal with later) and go back to purging my email queue.

**Comment by M66B** [comment]
There is a menu to open the link in the browser.

**Comment by M66B** [comment]
An option is to uninstall Chrome.

**Comment by markwmuller** [comment]
Oh, I see, actually it's really straight-forward. 

Thanks!
