### ISSUE TITLE
Set a default folder display name

### ISSUE THREAD

**Issue by heinhuiz** [M66B/open-source-email#135]
In folder properties, set a editable default display name instead of the current grey hint text. Default name can be current folder name.

Also, in edit/create account, defaults can be set, like Host name can default to imap.<domain name set above> and port number to 993. Same applies to edit/create identity; smtp.<domain name> and port 465. In most of the cases these will be the right settings.

**Comment by M66B** [comment]
Already done in a spare moment ;-)

Setting the host name is not a good idea IMHO though.

**Comment by heinhuiz** [comment]
:+1:
