### ISSUE TITLE
Browsing issues and breaks Manually synchronization

### ISSUE THREAD

**Issue by rancidfrog** [M66B/open-source-email#138]
When **_browsing_**  if connection is lost unexpected error popup appears:
![](https://i.imgur.com/ecrYsvY.png)

Also,
Browsing basically syncs the folder you open.
So, even when you have folder sync disabled if you open the folder it will sync.
So I do not see the point of having folder sync settings, as it will be overridden when you open folder.

How can I only have folders to sync to be manually.
As now there is no point in "**Synchronize now**" button either, since opening folder does exactly that.
Which breaks the whole point|idea of Manually synchronization and folder sync settings.

**Comment by M66B** [comment]
Browsing does only download messages visible on the screen and some more, so it is not the same as synchronizing. (Manual) synchronize will fetch all messages for the number of days specified.

What would you like to change to the message? It is maybe a little bit technical, but it is an unexpected error.

**Comment by M66B** [comment]
If browsing bothers you, you will be able to turn it off in the next release.
