### ISSUE TITLE
Feature request: Tagging

### ISSUE THREAD

**Issue by mbrasch** [M66B/open-source-email#139]
# Feature request: Tagging

Tagging (via IMAP KEYWORDs) would be nice. MailMate lets me define tupels of human readable tags and IMAP KEYWORDs, such as "Warte auf Antwort" and "waitingonreply". (In case of Gmail I can extend this with an lable.)

I use tagging to organize me (todo, inprogress, tobeanswered, urgent, etc. pp.). It would be nice to use these tags on my mobile device as well.

The UI could show virtual folders for every **used** tag.

**Comment by M66B** [comment]
Besides that JavaMail doesn't seem to support this and that general support by email providers in unclear, the goal is to keep FairEmail simple.

You can just create folders to achieve the same goal, but with advantage it will be compatible with most email clients.

**Comment by mbrasch** [comment]
Unlike the folder variant, with tagging I can (and do so) use several tags per mail.

With regards to the IMAP KEYWORDs, yes, some mail provide have a very poor KEYWORDs support. But many of the better ones let you define (nearly) as many keywords as you need.

But if JavaMail has no IMAP KEYWORD support… :/

**Comment by M66B** [comment]
Building an app is not only about features, but also about maintenance and support and this is not something that can be supported for a large number of users and a big variety in email providers.

FairEmail is open source, so maybe you can add it yourself.
