### ISSUE TITLE
The standard reply menu option should give some info about being a Pro-feature

### ISSUE THREAD

**Issue by ouzowtf** [M66B/open-source-email#144]
Selecting this option from the three dot menu of a message does nothing at the moment.
It should have a text hint "standard replies (Pro)" or show the pro feature page.

Selecting "standard replies" from the hamburger menu shows a blank page too.

**Comment by M66B** [comment]
Thanks. I will look into it.

**Comment by M66B** [comment]
Without pro features you can still add standard replies from the main navigation page, which is not empty, there is a orange plus button at the bottom.

**Comment by ouzowtf** [comment]
Ah, okay. The pro feature page is shown from the three dot menu of a message if a standard reply was created before in the main navigation page and then selected in the message itself.

But I think a hint for the needed pro feature should be more clear nevertheless.

**Comment by M66B** [comment]
I have decided to keep it as it is because the idea was to be able to see how it would work.
