### ISSUE TITLE
Simplify navigation

### ISSUE THREAD

**Issue by licaon-kter** [M66B/open-source-email#15]

**Comment by M66B** [comment]
Why? You can get out with back everywhere.

**Comment by licaon-kter** [comment]
To stop the app, to dismiss the service and notification, to escape the opression of the always connected age?😁

**Comment by M66B** [comment]
If you want to stop synchronization: disable synchronization of your account(s). If all accounts are disabled, the foreground service will be disabled, making the status bar icon go away.

New email notifications (not there yet) can be managed using Android.

**Comment by rancidfrog** [comment]
@m66b
There is an issue with back button as it cycles through everywhere you opened in app

**Comment by M66B** [comment]
@rancidfrog yes, I know. Patience ... everything is very new.

**Comment by M66B** [comment]
Using 'back' in the next version will always return to the unified inbox. Using 'back' on the unified inbox will close the UI.

Setup and compose run in separate activity. Especially compose should be closed on 'back' from the compose activity itself to prevent losing text.

Please let me know if this is how you would expect it.
