### ISSUE TITLE
Manually refresh/sync folder

### ISSUE THREAD

**Issue by rancidfrog** [M66B/open-source-email#16]
The only way to sync a folder it seems is to longpress folder and select sync:
a folder is either synced
![](https://i.imgur.com/TgQwQFw.png)
Or not,
![](https://i.imgur.com/5U9SPzr.png)

However, having the option to sync when you longpress on a folder or a sync/refresh button whilst inside folder would be convenient for the times you want to check a folder without syncing all the time.

**Comment by M66B** [comment]
This will be in the next release, with as extra that you can force send in the same way by long pressing the outbox.
