### ISSUE TITLE
OAuth for authentification

### ISSUE THREAD

**Issue by Primokorn** [M66B/open-source-email#17]
Hi,  
I use 2FA for GMail. The app asks me to create a specific password to be logged in.
Using [OAuth](https://en.wikipedia.org/wiki/OAuth) would be appreciated to avoid this extra step.

Thank you.

**Comment by M66B** [comment]
Signing in to Google requires Play services integration, which is unwanted considering the goal of the project.

https://developers.google.com/identity/sign-in/android/start-integrating
