### ISSUE TITLE
Show "No account, do setup one..."

### ISSUE THREAD

**Issue by licaon-kter** [M66B/open-source-email#18]
Steps:
* first install (or clean)
* Agree
* see Setup (but don't setup anything)
* press BACK arrow
* see "No messages"

**Comment by M66B** [comment]
This has been fixed in another way.

**Comment by licaon-kter** [comment]
In both view can you add "No account setup. Use + to add one" or smth?

**Comment by M66B** [comment]
You cannot see the message list anymore when there isn't an account setup, so there is just one view now, the setup view.

How about showing 'no accounts' where 'done' appears after an account has been setup?

**Comment by licaon-kter** [comment]
Not message list...the account&identity views

**Comment by M66B** [comment]
Yes, I understand you meant the setup view (=account/identities view).

Normally there will be 'done' under 'manage account' when at least one account is setup and enabled. My proposal was to display 'no accounts' (setup or enable) instead if there was nothing setup.
