### ISSUE TITLE
Setup - use default ports

### ISSUE THREAD

**Issue by licaon-kter** [M66B/open-source-email#19]
Steps:
* setup everything except port
* try to connect
* fails

[No error pops up](https://github.com/M66B/open-source-email/issues/4), albeit if I change to another app I can see the toast saying that it tried to connect to port 0 (zero?), I can also see the entry in NetGuard to "domain.tld" (but no port).

If no port specified, do use those in the hints (as expected?), 993 and 465.

**Comment by M66B** [comment]
I might do this, but hints are not meant as default values, but some people might see them like that. Otherwise the error message needs to be improved.

**Comment by licaon-kter** [comment]
Do they often change 993/465 no other ports?

**Comment by M66B** [comment]
In theory any port could be used, especially if you run your own email server, but these ports are pretty standard as far as standards go.
