### ISSUE TITLE
Password entry field add 'eye'

### ISSUE THREAD

**Issue by licaon-kter** [M66B/open-source-email#2]
....to show password

**Comment by M66B** [comment]
Done

**Comment by licaon-kter** [comment]
Great, but could you limit it on account setup (not account edit) ?

The security workflow assumes (or better said I assume) that once I entered the password and it's used, if I handle the device to someone, there's no way for that person can't see my password.

**Comment by M66B** [comment]
Also prevent copy and paste.

**Comment by licaon-kter** [comment]
Careful not to disable [autofill](https://developer.android.com/preview/features/autofill) though.

**Comment by rancidfrog** [comment]
Passwords are stored in email.db, easily accessed with open with textviewer.
Is there no better/safer way to keep it stored?

**Comment by M66B** [comment]
Without root permissions the database is not accessible and storing it in a file won't change anything. The database is a file too after all. I might look into encrypting the database later (see also the to do list on XDA).

**Comment by licaon-kter** [comment]
@rancidfrog I don't have root, they're protected by FDE, right?

**Comment by rancidfrog** [comment]
@licaon-kter not always. Depends on user setup and ROM used. Some ROMs run decrypted, no FDE nor FBE.

**Comment by M66B** [comment]
Normal Linux file permissions don't allow access by default. Encryption doesn't make it more secure in this case because you have unlocked your device when running apps.
