### ISSUE TITLE
Mark as unread - don't popup (new) notification

### ISSUE THREAD

**Issue by licaon-kter** [M66B/open-source-email#20]

**Comment by M66B** [comment]
It does (for me), but only for inboxes. I have been thinking about a setting per folder, but that would complicate things.

**Comment by licaon-kter** [comment]
I've said "please DO NOT notify me about the fact that I just marked an e-mail as unread"....I already know. 😁

**Comment by M66B** [comment]
As a reminder to read things. Anyway, for now I want to keep things as simple as possible and implement all basic features and stabilize stuff. Adding compose with attachments is much more important than this.

**Comment by licaon-kter** [comment]
I agree.

Another thing, say I mark as unread, see the notification, dismiss it.....but after a while I will see it again (no actual NEW mail received)...this is annoying. :(

**Comment by M66B** [comment]
That would be a bug. Any idea when that happens?

**Comment by licaon-kter** [comment]
Edit account name, OK - > popup

**Comment by licaon-kter** [comment]
Also, Folders-long press-enable sync (or modify days)-ok -> popup
