### ISSUE TITLE
Edit trashed new message

### ISSUE THREAD

**Issue by licaon-kter** [M66B/open-source-email#21]
...right now if you press Trashby mistake it will be gone

**Comment by M66B** [comment]
It will not be gone, but in the trash folder and can easily be restored. A nice opportunity to try it the new move operation ;-)

There will be a confirmation dialog on permanent deletes from the trash folder and for accounts without trash folder.

**Comment by licaon-kter** [comment]
I have several trash folders...but they're all emp

**Comment by M66B** [comment]
Are these folders marked as 'trash' in the folder list (as opposed to 'user') ?

**Comment by licaon-kter** [comment]
1 trash, 1 user

**Comment by M66B** [comment]
Trash should move the message into the trash type folder, but only if it is the same account. Cross account operations are not supported by IMAP.

**Comment by licaon-kter** [comment]
One account...

**Comment by M66B** [comment]
Then deleting should move the message to trash.

**Comment by M66B** [comment]
Did you enable sync for the trash folder? (Maybe this should be the default)

**Comment by licaon-kter** [comment]
Ok, that was it.

Yes it should be by default and the users should disable it as they please.

Also, I was expecting it to refresh when I enter it.

**Comment by licaon-kter** [comment]
Ok, so...
* start new message
* write something
* hit Trash
* reconsider
* go to Trash
* find out there's no way to continue editing

But you can Answer(?), Forward and Move it to any other folder THAN Drafts

**Comment by M66B** [comment]
Composing messages is still a little unfinished and is almost at the top of the to do list to work on.

**Comment by M66B** [comment]
In the next version it will be possible to edit trashed messages.
This will create a new draft because at least Google doesn't allow trashed messages to be moved to drafts.
