### ISSUE TITLE
No mails saved in sent folder

### ISSUE THREAD

**Issue by tanrak** [M66B/open-source-email#24]
Hi, first thanks for the great app.
After a little testing all seems to work fine but only mails won't save in the sent folder. The app recognizes the correct sent folder because i can see mails that i have sent with K-9.

**Comment by M66B** [comment]
Unsent/sent messages are currently shown as unread/read in the outbox.

Since identities are currently not linked to accounts (this might change), the question is which folder to put sent messages into.

Normally, the email server will report a new message in the sent folder back to the client. My question is if there is a folder marked 'sent' (not 'user') in your folder list.

**Comment by tanrak** [comment]
> Unsent/sent messages are currently shown as unread/read in the outbox.

Ah, yes. I see it in the app.

> My question is if there is a folder marked 'sent' (not 'user') in your folder list.

I would say yes. In the Webmail from my Provider the config looks like this:

![mail_folder](https://user-images.githubusercontent.com/35105392/43771325-3690c492-9a3f-11e8-8b93-8738f44ee962.png)

**Comment by M66B** [comment]
Can you show me the sent folder in the app as well?

**Comment by tanrak** [comment]
> Does the sent folder show up with 'Sent' to the right bottom in the folder list?

Yes.

![sent_folder](https://user-images.githubusercontent.com/35105392/43773304-9965eede-9a45-11e8-8f96-d058b4f04f97.png)

**Comment by M66B** [comment]
I meant the list with folders, not the list with messages ...

**Comment by tanrak** [comment]
This looks so...

![sent_folder](https://user-images.githubusercontent.com/35105392/43773545-5254e3f0-9a46-11e8-95c4-694c69f21749.jpg)

**Comment by M66B** [comment]
Okay, there is a folder with the type 'Gesendet', named 'Sent'. Normally sent messages should appear in this folder. Can you check if sent messages appear on the website and in the app in this folder?

**Comment by tanrak** [comment]
If i send a mail in webmail then the message appear in this folder on the website and in your app.
If i send a mail in your app the message only appear as marked in Postausgang but not in Gesendet/Sent in the app or on the website.

**Comment by M66B** [comment]
Okay, this is clear. I will see if I can solve this.

**Comment by tanrak** [comment]
Ok, thanks for the work.

**Comment by M66B** [comment]
This should be fixed in the next release
