### ISSUE TITLE
Logo offer 

### ISSUE THREAD

**Issue by familqasimov** [M66B/open-source-email#25]
Hi sir Marcel Bokhorst. I'm graphic designer. I would like to offer logo. If you like, I can give you with great pleasure all the formats of the design free. If you want a change please specify.

![untitled-1](https://user-images.githubusercontent.com/36432269/43797527-cc0bc162-9a98-11e8-9362-c15af7092a44.png)

**Comment by xoxys** [comment]
Like it and would also love to see a little bit more shiny logo.

**Comment by M66B** [comment]
@familqasimov thanks for the offer!

The name of the app is not determined yet, but I am thinking about the suggested Ishmail.

@xoxys I prefer simple, which is also better for launcher icons.

**Comment by familqasimov** [comment]
I think you might like one of them.

![untitled-2](https://user-images.githubusercontent.com/36432269/43811909-05bd9f34-9ad0-11e8-8acd-cfb551fb209a.png)

Best regard
Famil
