### ISSUE TITLE
Don't show operations pending when there are none

### ISSUE THREAD

**Issue by rancidfrog** [M66B/open-source-email#26]
I swipe notification of new mail from notification bar:
![](https://i.imgur.com/lZerNQr.png)
And it just reappears, immediately.
Same exact notification.
Even when I click on notification which takes me to inbox, notification still there.
Normal procedure would remove notification if you click on it.

**Comment by M66B** [comment]
Which version are you using?

**Comment by rancidfrog** [comment]
It might be specific case, as after I checked one of the mail to see if it will update to 7 new messages, it did not. Just disappeared.
Not sure how to reproduce.

**Comment by M66B** [comment]
Please keep an eye on it and if it happens again let me know, preferably with the details leading to the situation.

**Comment by M66B** [comment]
Sync off is the explanation. The last seen timestamp will only be updated from accounts with sync on otherwise new email of those account would potentially not show up after enabling sync. What should be done is setting the last seen timestamp on disabling sync.

**Comment by rancidfrog** [comment]
I still get the 0 operations pending, though
![](https://i.imgur.com/zujfmr8.png) 
Even with sync on
![](https://i.imgur.com/aGv8V6w.png)

And, am unable to swipe it away. 
Clicking it takes you to inbox but does not remove notification.

**Comment by M66B** [comment]
Please see this new FAQ:
https://github.com/M66B/open-source-email/blob/master/FAQ.md#FAQ2

The new email and the status notification are different things.

**Comment by licaon-kter** [comment]
If 0 pending maybe don't say "0 pending", seems useless.

**Comment by M66B** [comment]
I still says everything is okay.

**Comment by rancidfrog** [comment]
Exactly, it should only be present when active. When there are 0 operations pending notification should either be removed or switch to non-permanent so that users can swipe it away since no active operations anyway

**Comment by licaon-kter** [comment]
Ok, but what's the point of zero pending?

**Comment by M66B** [comment]
That you know that all email has sent for example.

See also here:
https://github.com/M66B/open-source-email/blob/master/FAQ.md#FAQ3

I think if there needs to be a status bar notification it can better contain as much as useful information and "0 pending" is useful information IMHO.

**Comment by licaon-kter** [comment]
No operations pending (no message) means they've all been "operated", whatever. :)

**Comment by rancidfrog** [comment]
@M66B @M66B I agree it can be useful, but it is not a priority anymore. So yes having a notification with Operations completed, i.e. mail Sent, should be appearing, but it should not be persistent anymore, meaning now since operations have completed it should be swipe-able.
As for new mail issue. It should be then a separate persistent notification. With a clear body.
Having completed operations separate and the main persistent synchronizing notification makes it more clear.

**Comment by M66B** [comment]
@rancidfrog the notifications are already separate.

**Comment by rancidfrog** [comment]
Maybe just have different message in body, rather than 0 operation(s) pending?
In main notification, that is.

**Comment by rancidfrog** [comment]
Closed this issue, as it is just an issue with body message of notification, as m66b explained.
