### ISSUE TITLE
Split screen resets input fields

### ISSUE THREAD

**Issue by licaon-kter** [M66B/open-source-email#3]
I was switching between Netguard and the app since it does not connect and I don't see any errors, and I got tired so I started splitview only to see that all my text from the "Send" page input fields view got cleared.

**Comment by M66B** [comment]
This should be fixed.

**Comment by licaon-kter** [comment]
Not fixed, please reopen.

**Comment by M66B** [comment]
If possible, can you show me this in a video?

**Comment by M66B** [comment]
With the above commit saved drafts will be restored, but not changes made after saving.

**Comment by M66B** [comment]
Fixed by https://github.com/M66B/open-source-email/commit/f85ef0579bf12d11834c30f7ce1b533e2c2848fa
