### ISSUE TITLE
Allow attachment saving

### ISSUE THREAD

**Issue by licaon-kter** [M66B/open-source-email#32]
Now I can see a PDF but trying to Share it from Document Viewer will fail with "unable to find src" or smth, because you save it "somewhere" temporary.

**Comment by licaon-kter** [comment]
Also, PNG files are not opened with the Gallery like JPGs (the Gallery app is associated and it can open PNGs just fine otherwise)

**Comment by M66B** [comment]
Regarding the error message in the first comment: do you have more details?

Regarding your comment about PNG files: please enable debug mode and tell me what the file type of the attachment is.

**Comment by licaon-kter** [comment]
Regarding PNGs, I can attach one and open it from the compose draft view.

I can't test the PNG in that received email that didn't work as I can't update my inbox (it's still stuck on Aug 16 'cause of #41)

**Comment by M66B** [comment]
This will be part of the next release.
