### ISSUE TITLE
Forward with attachments

### ISSUE THREAD

**Issue by licaon-kter** [M66B/open-source-email#33]
...as expected

**Comment by M66B** [comment]
Not all email apps do.

Drafts are automatically uploaded, so this can be ugly if you received a lot/large attachments, especially if you are on a limited mobile data bundle.

**Comment by licaon-kter** [comment]
Show a dialogue, maybe not all e-mails need the attachments on forward. 🤔>

**Comment by M66B** [comment]
For now you can download attachments and attach them to a new message when necessary.

**Comment by M66B** [comment]
Downloaded attachments will be forwarded in the next version.

**Comment by markwmuller** [comment]
FWIW, I'd prefer to have a dialogue warning me that the attachments are not forwarded, or ideally a dialogue that appears, when I select "forward" that asks if I'd like to forward the attachments too (and if I say "yes", it'll download them as necessary).

**Comment by M66B** [comment]
@markwmuller create an issue for this and I will see what I can do.
