### ISSUE TITLE
Show all file providers on new mail file attach

### ISSUE THREAD

**Issue by licaon-kter** [M66B/open-source-email#34]
Like Total Commander or Gallery etc

**Comment by M66B** [comment]
Files are select by using the Android storage access framework (to prevent requesting file permissions), so the dialog shows whatever Android can show (including Google Drive for example), so I am wondering what is exactly missing and why.

**Comment by licaon-kter** [comment]
Eg. The list should include apps like https://github.com/ianhanniballake/LocalStorage

**Comment by M66B** [comment]
Then that app should accept view (share) requests from FairEmail. This is not something that can be fixed by FairEmail.

**Comment by M66B** [comment]
A little background: FairEmail shares a file using a file provider and specifying the right file type. It is up to the receiving app to accept the share. FairEmail cannot force this.

See here for the implementation details:

https://developer.android.com/reference/android/support/v4/content/FileProvider

**Comment by M66B** [comment]
This is to avoid asking for storage permissions (which is really not of these days anymore).

**Comment by licaon-kter** [comment]
You see Google Drive in your list?

**Comment by M66B** [comment]
Files are shared for viewing, not for storing, so no.

**Comment by M66B** [comment]
I will add a download (store) option (long press?) later.

**Comment by licaon-kter** [comment]
This issue is not about download (that's another one but shares the idea)...not sure why you keep saying it?!

**Comment by M66B** [comment]
It is because people on XDA several times expressed they want a download.

Anyway, files are sent through the storage access framework as they should.

**Comment by M66B** [comment]
Just to check: you should be able to view for example PDF files with a PDF viewer installed, right?

**Comment by licaon-kter** [comment]
And I do, but let's keep that in #32

**Comment by M66B** [comment]
Then viewing works as should, so I am closing this issue. What you want is "download" or "store" as in the other issue.

**Comment by licaon-kter** [comment]
I don't understand....this issue is about allowing me to **attach** any file on my device **not only** those in "Downloads" and this doesn't work at the moment.

**Comment by M66B** [comment]
Then I misunderstood. I can select to attach from Google drive and internal storage.

The same applies: FairEmail cannot force what the storage access framework shows.

What can you select? Did you try the menu to show internal storage?

**Comment by licaon-kter** [comment]
Ok, I've reinstalled the app linked above and now it's shown (as Home) and also Termux is shown too, but the app list is shorter, missing things like TotalCommander, stock Gallery, stock SoundRecorder, stock Files app.

**Comment by M66B** [comment]
As said before: FairEmail has no control over this.
