### ISSUE TITLE
Show error messages in a view banner

### ISSUE THREAD

**Issue by licaon-kter** [M66B/open-source-email#4]
...instead of toasts...I mean I guess it has toasts, I saw them once when I switched to Netguard, while in app there was no error message, maybe it's the password, maybe Netguard 

(I checked StartSSL and that's why it did not work)

**Comment by M66B** [comment]
Initially [Snackbar](https://developer.android.com/training/snackbar/action)s were used, but the text size was too limited to show the full error details.

I will see how I can solve this.

**Comment by M66B** [comment]
I see no better way. Snackbars are used where possible, but just have limited size.
