### ISSUE TITLE
Can't configure SMTP with disroot.org

### ISSUE THREAD

**Issue by smigima** [M66B/open-source-email#42]
Ok, so I have e-mail account on disroot.org service. 

IMAP: disroot.org | SSL Port 993 | Authentication: Normal Password
SMTP: disroot.org | STARTTLS Port 587 | Authentication: Normal Password
POP: disroot.org | SSL Port 995 | Authentication: Normal Password

IMAP is working well (better then in K9, I can see my folders in INBOX finally) but can;t configure SMTP.
I put all the informations above, check STARTLS, but after a while it says that connecton failed due a timeout.

**Comment by smigima** [comment]
Thanks for quick reply!
After disabling AfWall+ I'm still getting the same error. Also I've checked in second phone with the same result.
So I don't think it's because my software. 
Anyway, thanks for good work, I'll come back later to check some future versions.

**Comment by nr458h** [comment]
Disroot works on my set up. Are you sure you put in the right credentials? The serveradress for example is disroot.org and not imap.disroot.org or also an often upcoming error is the username is only the part before the @.
Hopefully this was helpful
