### ISSUE TITLE
PGP OpenKeyChain - Encryption

### ISSUE THREAD

**Issue by genofire** [M66B/open-source-email#43]

**Comment by M66B** [comment]
I will look into this later, but currently this has no priority.

**Comment by M66B** [comment]
https://www.openkeychain.org/

**Comment by genofire** [comment]
Excatly.
All right ;) - till then i could not change complete away from k9

**Comment by M66B** [comment]
FairEmail is not ready for production yet, which is also why this currently has no priority.

**Comment by KonradIT** [comment]
Definitively +1 for OpenKeychain support, this is what K-9 supports and K-9 has not been updated in 7 months according to F-Droid.

**Comment by licaon-kter** [comment]
@KonradIT K-9 has looooong betas for some reason, that's the last version on Google too.

**Comment by KonradIT** [comment]
OpenKeychain provides an Intent API: https://github.com/open-keychain/open-keychain/wiki/Intents

**Comment by M66B** [comment]
Beta version 0.24 has basic OpenPGP support. There are a few minor issues that will be fixed in the next release. OpenPGP support will be a pro feature.

**Comment by genofire** [comment]
Do you have a way of recieving donations?

**Comment by M66B** [comment]
Yes, see 'pro features' in the navigation menu or just here:

https://email.faircode.eu/pro/

**Comment by M66B** [comment]
I am opening this issue again to remind myself to add encryption support for 'encrypted.asc' attachments.

**Comment by licaon-kter** [comment]
@genofire Press Donate in F-Droid->Fairemail details ;)

**Comment by M66B** [comment]
There is already an issue #66 for improvements, so I am closing this one again.

**Comment by M66B** [comment]
Can you please explain why you want to encrypt for your recipient?
You are supposed to encrypt messages with your key.

**Comment by genofire** [comment]
It does not make sense, that i send a E-Mail to somebody, which could only opened be me.

---

I want to send a encrypted E-Mail to somebody, so i use the public keys of my recipient.
On this way, they could decrypted my E-Mail with there private key.

![async crypto](https://idea-instructions.com/public-key.png)

**Comment by genofire** [comment]
Maybe a option in Settings like encrypt **always** or encrypt **if trusted** is also a good idea.
(Which is only possible if recipient's keys are in stored in OpenKeyChain)

**Comment by M66B** [comment]
You are right and I will fix this this weekend.
