### ISSUE TITLE
Debug system - unusable

### ISSUE THREAD

**Issue by licaon-kter** [M66B/open-source-email#44]
Might be a device issue (Mate9/Oreo), but I can't really use it.

When there's an issue it goes like this:
* enable debug
* trigger the issue
* about - debug
* draft view with days (since the last reboot!!) of content
* try to scroll to the end, scroll, scroll (no fast scroll??)
* give up after 2 minutes
* switch to Github to add to an issue
* switch back to FairMail
* black screen, app died
* FairMail draft pops up: `parcel error`
* delete it
* go to Drafts
* see 5 drafts with logs
* open one, wait 30 seconds to load
* press Trash icon...oh wait it does nothing
* see Android dialogue `kill app/wait`, choose wait
* press Trash as soon at it lets you
* repeat for several minutes do delete them all
...

Can you limit the log to the last hour, last day tops?

**Comment by M66B** [comment]
I will see if I can limit the logcat size.

**Comment by M66B** [comment]
Test version:

https://email.faircode.eu/FairEmail-v0.20-release.apk

Other changes:

https://github.com/M66B/open-source-email/compare/0.20...78cd6c8e7987d025805c0ac766a4787833b36691

**Comment by licaon-kter** [comment]
Thanks
