### ISSUE TITLE
Add import/export settings

### ISSUE THREAD

**Issue by licaon-kter** [M66B/open-source-email#45]
...as with multple accounts is no fun to enter servers and credentials.

**Comment by M66B** [comment]
Since the database structure has been stabilized and the setup has been simplified, there is less need to add this.

**Comment by rancidfrog** [comment]
This will also be useful when switching phones. As phones nowadays last max 2 years then hardware/software problems starts to arise, forcing you to a new phone.

**Comment by M66B** [comment]
Selecting a provider, typing in your user name and password once in two years isn't that hard.

**Comment by Kelvino9** [comment]
Adding a provider is definitely not troublesome even if it would happen once a week, but setting up the folder synchronization for multiple folders and accounts is. Same for goes for multiple identities, standard replies and probably more settings for upcoming features. An import/export feature for more then just the provider setup would be useful.
