### ISSUE TITLE
Let account folders be expandable

### ISSUE THREAD

**Issue by Sonic112** [M66B/open-source-email#46]
Let account folders be expanded below the account instead of on a separate page

**Comment by M66B** [comment]
I am not sure what you mean, so could you explain in more detail what you want?

**Comment by Sonic112** [comment]
![screenshot_20180824-095tg510](https://user-images.githubusercontent.com/42668093/44572906-7f1e9600-a785-11e8-8c37-c27c34c2efe1.png)
Sorry, something like this, do it make sense now?

**Comment by M66B** [comment]
You can view the folders by tapping on the account name in the navigation drawer menu or for the primary account by tapping on the folder icon in the action bar.

I don't see what should be added to this, but please tell if you think this is insufficient.

**Comment by Sonic112** [comment]
I understand. It's probably just a personal preference

**Comment by M66B** [comment]
I guess you need to get used to it, but let me know if you have new insights.
