### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by omideleayo** [M66B/open-source-email#48]
Hi
I would like to add a privacy policy document for your project at my leisure to encourage open source developers.
Might also try and make the FAQs section more extensive

**Comment by M66B** [comment]
That would be very welcome.

The current privacy policy is here (because the Play store requires a web page), but should be moved to the app (too): https://email.faircode.eu/privacy/

**Comment by omideleayo** [comment]
Oh cool, will be in touch

**Comment by M66B** [comment]
If you want to work on this, just create pull requests.

**Comment by M66B** [comment]
FairEmail is getting stable and most features are there, so this is a good moment to work on the documentation ...
