### ISSUE TITLE
Html compose inline images

### ISSUE THREAD

**Issue by Sonic112** [M66B/open-source-email#49]
Availability to compose & view text in both Html and plain text would be nice.

**Comment by M66B** [comment]
Which html elements would you like to use?

On XDA there was asked for:

* Bold
* Italic
* Inline images

**Comment by Sonic112** [comment]
And fonts/style I'm not sure of the right term, (maybe even emojis)

**Comment by rancidfrog** [comment]
I would really like to see the ability to compose inline images.

**Comment by M66B** [comment]
Bold/italic will be in the next version.

**Comment by M66B** [comment]
For if when somebody want to look into this: inline images with data uris doesn't work.

**Comment by M66B** [comment]
Font size

**Comment by rancidfrog** [comment]
_Simple Java Mail Features_:

http://www.simplejavamail.org/#section-embedding

```

Embedding images

Embedding images is simple, but you have to add the placeholders in the HTML yourself.

currentEmailBuilder.withEmbeddedImage("smiley", new FileDataSource("smiley.jpg")); // this example is included in the demo package in MailTestApp.java String base64String = "iVBORw0KGgoAAAANSUhEUgAAA ...snip"; currentEmailBuilder.withEmbeddedImage("thumbsup", parseBase64Binary(base64String), "image/png"); // the corresponding HTML should contain the placeholders <p>Let's go!</p><img src='cid:thumbsup'><br/> <p>Smile!</p><img src='cid:smiley'>


```

**Comment by M66B** [comment]
FairEmail is not using simplejavamail.

**Comment by rancidfrog** [comment]
I know.
Just a reference.
If someone wants to see how it has been implemented. Or to test if it works fine on android.

**Comment by M66B** [comment]
Font size is not that important and is very low priority.

**Comment by bjo81** [comment]
Writing in plain text seems impossible?

**Comment by M66B** [comment]
Please don't misuse issues for your questions. XDA is for questions.
