### ISSUE TITLE
Add tooltips on long-press icons

### ISSUE THREAD

**Issue by licaon-kter** [M66B/open-source-email#5]
I can guess what they do but better be sure.

**Comment by M66B** [comment]
There are now titles for the main message actions.
Adding titles to the other actions would take up to much screen space.

**Comment by rancidfrog** [comment]
Longpress tooltips only apply to actionbar at the moment:
Folders,
![](https://i.imgur.com/TUtoEvp.png) 
CC,
![](https://i.imgur.com/LBAC02V.png)

However the other buttons do not have any,
![](https://i.imgur.com/TcJtnrd.png)
