### ISSUE TITLE
Onboarding introduction for new users

### ISSUE THREAD

**Issue by Namnodorel** [M66B/open-source-email#52]
If you want to make the setup/inteoduction easier for such users, you likely need to _really_ hold their hand. I'm thinking of the nowadays popular "onboarding", or an introduction at the first start of the app. Most Google apps have it, and many others in the Play Store as well.

That includes usually: Going through every important setting with the user one by one. Fullscreen, big font. No more than one or two instructional sentences per page.

For FairMail, the first page could be something along the lines of "Welcome to FairMail! The E-Mail client that keeps things simple and respects your privacy. Let's started!"
then for account selection "First, choose your E-Mail provider from the list below". With a list (not dropdown!) of supported providers. Preferably big buttons, and/or provider icons next to their names so users can recognize theirs faster. And at the bottom of the list "My provider is not on this list."

Depending on what the user selected, the majority of users will then have to do nothing but enter their mail and passwords and don't need to think about mail protocol stuff at all - if you select a preset provider, the fields port, server etc. are not prefilled but aren't even there so no user gets confused about whether or not they are expected to do something.
For identities, on the next screen there could be a prominent option "use the same provider as before", which then tries to setup the identity with the earlier provided credentials. Finally, one or two more pages for theme and contact permission, and even the least technical user should have managed to set everything up.

There are a couple of libraries which make adding such an intro to an app trivial. Examples include:
https://github.com/apl-devs/AppIntro
https://github.com/TangoAgency/material-intro-screen
https://github.com/HeinrichReimer/material-intro/

**Comment by Namnodorel** [comment]
Well, of course ultimately it's your call.

I personally think that a full guide through the process would be best in terms of UX, but the suggestion from the XDA post is still better than what we have now.

**Comment by M66B** [comment]
When the dust has been settle down, I will work on a full setup wizard.

**Comment by nussbaumer** [comment]
Won't it bloat the apps size?

**Comment by M66B** [comment]
@nussbaumer no really compared to the current size, so no worries.

**Comment by M66B** [comment]
With these changes setting up an account will be selecting a provider and entering a username and password only, with the option to drill down advanced settings for more experienced users. Setting up an identity is just entering a name and selecting a linked account, again with the option to drill down advanced settings.

I like to keep the setup screen because it provides an overview of what to do and why to do.

I also like to keep the initially empty account/identity list with the 'plus' action button, so people are aware that they can add multiple accounts/identities.
