### ISSUE TITLE
[Feature Request] Star messages

### ISSUE THREAD

**Issue by nr458h** [M66B/open-source-email#55]
It would be nice to be able to delete or star or move the mail to another folder by swiping left or right over the mail.

**Comment by nr458h** [comment]
Thanks for the quick implementation. Works fine for me 
 :+1:

In my opinion it would be more helpful to show the archive or the trash icon while swiping instead of showing the message "moved successfully to archive" after the action. I hope it is understandable what I mean. For example the outlook app uses this feature

Thanks anyway for your work and making it open source!

**Comment by M66B** [comment]
Star messages is a duplicate of #9 
Icons/colors are a duplicate of #59
