### ISSUE TITLE
[Feature Request] Show details in Notification

### ISSUE THREAD

**Issue by nr458h** [M66B/open-source-email#57]
It would be nice to get a short overview about the received E-mails in the notification. For example sender, subject and probably the first line of the mail.

**Comment by M66B** [comment]
This is a pro feature.

https://email.faircode.eu/#pro

**Comment by nr458h** [comment]
Sorry didn't so this :relaxed:

**Comment by M66B** [comment]
These kind of things are announced in the XDA FairEmail thread.
