### ISSUE TITLE
[request] add signature

### ISSUE THREAD

**Issue by chantoine** [M66B/open-source-email#58]
Please add a signature. Maybe more important than standard answers. Thanks

**Comment by M66B** [comment]
Personally I have nothing with signatures. Anyway, for the moment you can use standard answers for signatures too.

**Comment by chantoine** [comment]
It's a good trick, indeed ! Thanks

So... all it would take is a "standard answer" button accessible during writing to add the signature function :-)

**Comment by M66B** [comment]
Signatures are at account level, not identity level, so you don't have to enter the same signature for all identities linked to the same account.

**Comment by Kelvino9** [comment]
Thanks for adding signatures!
Adding a signature on account level makes sense for ease of usage, but it would be logical to implement it under identities. Signatures are only used for outgoing emails and therefore should be located within the Identities (SMTP setup).

If someone use different identities for the same account it usually serves a specific purpose. For example differentiating work, private, club activity recipients who shouldn't receive an email from the same email address. An unified signature might not fit all recipients and would be impropriate or misleading to recipients of a different identity. Friends or club members shouldn't receive office fax number or office phone number for example if the get a mail from the same account with different identities, but a unified signature.

**Comment by M66B** [comment]
The problem with that is that the signature needs to be changed on changing identities while composing a message.

**Comment by Kelvino9** [comment]
Recurring signatures could be handled and assigned to identities by a drop down menu similar to providers. 

Could signatures be applied on send rather than on selection and composing?

**Comment by M66B** [comment]
When replying/forwarding it is difficult to determine where to insert a signature.

**Comment by M66B** [comment]
Replacing an existing signature, possibly modified by the user, would even be a greater challenge.

**Comment by Kelvino9** [comment]
True, so for multiple identities it is wise to use standard replies feature instead as a way to individualize signatures per identity? (Have not used it so far)
