### ISSUE TITLE
Allow styling and Javascript on demand

### ISSUE THREAD

**Issue by Primokorn** [M66B/open-source-email#64]
Some emails include clickable elements using Javascript.
Since it's disabled by default for security reasons we can't click on those links. The only solutions are:
• using another email app to handle those links
• opening our web browser to read the email

A button like "Show images" to enable styling/Javascript *on demand* would be a better solution :)

Thanks!

**Comment by M66B** [comment]
I have added a menu to 'show original' message for this. It will show the original message in a webview with scripting enabled. If you have a suggestion for a better menu title, please let me know.
