### ISSUE TITLE
Decryption behaviour could be simplified

### ISSUE THREAD

**Issue by geronimoge** [M66B/open-source-email#66]
Behaviour could possibly be simplified

IS
1. open the mail and see no content but attachments.
2. click the little download button at attachment *.asc.
3. click the little eye button at attachment *.asc.
4. choose an app to decrypt (OpenKeychain).
5. type in the password to decrypt.
6. choose in the list, which now decrypted part you want to see (propably 'text').
7. switch back to FairEmail (where you still can't see the content of the mail).
8. repeat steps 1, 3, 6 when you want to see the content (e.g. text) again.

COULD
I personally like the behaviour from K9. There it's just one or two steps:

1. When you open an encrypted mail it tells you so,  OpenKeychain is opening the dialog and and you can type your pw to decrypt.
2. After that the decrypted mail is shown as a 'normal mail' with all oft its 'real content and attachments' within K9.
3. When you answer or forward this mail you can choose, if you want to do that encrypted or decrypted.

**Comment by M66B** [comment]
After this commit you can decrypt 'encrypted.asc' with one tap (two if you count downloading the attachment as well).

Encrypted attachments are not supported yet.
