### ISSUE TITLE
LED Notifications

### ISSUE THREAD

**Issue by ghtux** [M66B/open-source-email#67]
Hi.

Basic LED notification support would be nice.
Tried to force it via settings but didn't work.

System: Los 14.1, android 7.1

**Comment by M66B** [comment]
There are less and less devices with a notification LED, so this is not high on my priority list.

**Comment by M66B** [comment]
Notification LEDs are slowly disappearing, so I am not going to add this. Adding this would also require adding an option for the people who don't want a notification light and the goal is to have as little as possible options.
