### ISSUE TITLE
Attached images (.jpg) do not open in viewer

### ISSUE THREAD

**Issue by sas-3** [M66B/open-source-email#68]

**Comment by sas-3** [comment]
Hi, if I press the eye icon, I get a black screen (see first screenshot). Pressing the the dots says open with and then I get an xml-error. FairEmail: 0.32Android: 7.1.1 (SDK 25)Brand: bqManufacturer: bqModel: Aquaris XProduct: bardockDevice: bardockHost: bqbot6Display: 1.9.0_20180621-2036Id: NMF26FThx sasThu Aug 30 23:35:08 GMT+02:00 2018 M66B/open-source-email :Device? Android version? Gallery app? What if you save them?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.￼

**Comment by M66B** [comment]
Attachments cannot be added by replying to a GitHub notification.

**Comment by M66B** [comment]
Which XML error do you get exactly and what type of file are you trying to open? Which viewer app should be used?

**Comment by sas-3** [comment]
Hi,
the error says:

XML Error in line 9: unterminated entity ref (position: Text @9:29 in java.io.BufferedReader@a1847f9

It's a jpeg default gallery is simple gallery



On 30 August 2018 23:42:18 CEST, Marcel Bokhorst <notifications@github.com> wrote:
>Which XML error do you get exactly and what type of file are you trying
>to open? Which viewer app should be used?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/M66B/open-source-email/issues/68#issuecomment-417476404

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by sas-3** [comment]
Could also be a problem with my default gallery app, since I tried and installed k9 mail, which shows similar behaviour, although everything works when using Gmail.
