### ISSUE TITLE
[FR] M$ Exchange / ActiveSync support

### ISSUE THREAD

**Issue by ildar** [M66B/open-source-email#69]
I see FAQ says it's not yet supported.
So created this FR to track this feature.
Have any ideas on it?

**Comment by M66B** [comment]
The problem with this is that there are hardly any decent Java libraries for this.

There is a very old Google implementation here:
https://android.googlesource.com/platform/packages/apps/Email/+/froyo/src/com/android/exchange/

If you can find a recent and maintained Java library please let me know.

Exchange supports IMAP too, if the administrator enabled it, so this is not a big issue.

**Comment by M66B** [comment]
DavMail is more a gateway that a client, so this is not usable.

See above for a link to the very old Google code, which is the implementation of the Exchange account. The problem is that nobody maintains it.

**Comment by ildar** [comment]
But I still see it in Android at least version 7. You sure it's abandoned?

**Comment by M66B** [comment]
I am sure because there was nothing interesting committed in years, check here:
https://android.googlesource.com/platform/packages/apps/Email/+log/master

**Comment by M66B** [comment]
For now there is not enough support for this project to justify putting effort into this.
