### ISSUE TITLE
Forward, Reply, Reply All, New Mail - trash icon can't be pressed

### ISSUE THREAD

**Issue by licaon-kter** [M66B/open-source-email#7]

**Comment by M66B** [comment]
Works for me. Please provide more details.

**Comment by licaon-kter** [comment]
Albeit it works if I open a draft from the Drafts folder.

**Comment by M66B** [comment]
So, when doesn't it work?

**Comment by licaon-kter** [comment]
New mail via orange icon - not
See an email - press forward/reply/replyall - not

**Comment by M66B** [comment]
By email with video:
> (for some reason my ROM refuses to "show touches"
> 
> Steps:
> I write the texts
> Long press send (but me away so it does not trigger)
> Long press save as draft
> Long press trash (no animation nor action on touch)

Can you please reproduce the problem and send me the debug information?

**Comment by M66B** [comment]
Should be fixed.

**Comment by licaon-kter** [comment]
Fixed, thanks
