### ISSUE TITLE
Sync manually

### ISSUE THREAD

**Issue by Glops94** [M66B/open-source-email#70]
if possible to display email box in the menu even if the automatic syncronization is disabled in the configuration settings (to save battery) and have the ability to sync manually (for example just pulling the upper part of the eran)

**Comment by M66B** [comment]
For now you can leave the account enabled and disable synchronizing of all folders.

**Comment by rancidfrog** [comment]
Great.

**Comment by M66B** [comment]
Long press on the folder to sync.

**Comment by Glops94** [comment]
thank you very much
