### ISSUE TITLE
Mail providers from Germany

### ISSUE THREAD

**Issue by publicmoneypubliccode** [M66B/open-source-email#78]
Here are some more email providers from Germany which you might want to add:

Telekom:

IMAP: secureimap.t-online.de, Port: 993
SMTP:	securesmtp.t-online.de, Port: 	465
Source: https://www.telekom.de/hilfe/festnetz-internet-tv/e-mail/e-mail-server-e-mail-protokolle-und-e-mail-einrichtung/posteingangsserver-und-postausgangsserver?samChecked=true

Web.de:

IMAP: imap.web.de Port: 993
SMTP: smtp.web.de Port: 587
Source: https://hilfe.web.de/pop-imap/imap/imap-serverdaten.html

Freenet:

IMAP: mx.freenet.de Port: 993
SMTP: mx.freenet.de Port: 587
Source: https://kundenservice.freenet.de/artikel/1869

1&1:

IMAP: imap.1and1.com Port: 993
SMTP: smtp.1and1.com Port: 587
Source: https://help.1and1.com/e-mail-and-office-c37589/1and1-mail-basic-c37590/using-the-product-c85088/e-mail-software-setup-credentials-a616889.html

I hope that this is any help for you. I can't check these out by myself because of missing accounts. The data was always taken from the providers website itself. 
Let me know if I should provide more providers or informations.

**Comment by M66B** [comment]
Thanks for the effort, but I will add tested providers only.
