### ISSUE TITLE
[Feature request] Mark read by swipe

### ISSUE THREAD

**Issue by s3axel** [M66B/open-source-email#80]
Would it be possible to configure "right swipe" to be either archive or "mark read" ?

Personally I seldom use the archive option, but I quite often receive mails that I want to keep but also know their content and want to mark as read quickly (e.g. amazon order confirmations etc)

Thanks,
        Axel

**Comment by M66B** [comment]
Next version will have long press to mark read/unread.

**Comment by M66B** [comment]
See also #59
