### ISSUE TITLE
[Feature request] Automatically download small attachments

### ISSUE THREAD

**Issue by s3axel** [M66B/open-source-email#81]
One of the things I love about the approach of Fairemail is the "offline reading" feature.

Would it be possible to give a selectable option to download attachments as well as the messages themselves ? Maybe with a limit (like 1M per attachment) ?

Would be greatly appreciated :), thanks,
        Axel

**Comment by M66B** [comment]
Actually this is on my to do list.

It won't be 1MB though, but 32 KB.

**Comment by s3axel** [comment]
Thanks for your comment, happy to hear that :) Are you sure about the size, though ? Even some ordinary PDF-attachment is rather in the hundred-KBs range...

Of course its your design decision, I'm happy to take whatever feature is given :)

**Comment by M66B** [comment]
I am sure about the size because I have to take care of people on limited plans too. Also, synchronizing messages should not be delayed too much by downloading attachments. Even Google is slow with attachment downloads.
