### ISSUE TITLE
Add icons or text for swipe actions on mails for better UX

### ISSUE THREAD

**Issue by ouzowtf** [M66B/open-source-email#84]
It was mentioned in the XDA thread already, but I did not find a GitHub issue for it.

For better UX it would be nice if the swipe actions could show a visual hint in the free space like an icon or text to better teach the user which action he performs at the moment.
Personally I can't remember if trash or archive is left or right swipe, even if you told me just one minute ago :sweat_smile:

**Comment by M66B** [comment]
Duplicate of #59

**Comment by ouzowtf** [comment]
OMG, I'm sorry.
I promise to search better the next time :disappointed:
