### ISSUE TITLE
[FR] Show subfolders of an inbox in the unified inbox

### ISSUE THREAD

**Issue by Kelvino9** [M66B/open-source-email#87]
Currently I have my inbox separated into several subfolders to sort incoming mails with certain topics in specific folders. With the current state of FairEmail I'm not receiving any notifications of incoming emails, neither am I able to view them in the unified inbox. Technically these subfolders are still part of the same inbox.

As of now I only have the choice of either missing a major portion of my incoming emails or I stop sorting my incoming emails entirely resulting in a cluttered single inbox. Both options are a significant interruption of the practicability of an unified inbox. Unfortunately this is the one reason why I can't use FairEmail as a full replacement for AquaMail or K9-Mail right now. Nevertheless it's a fantastic mail app for many users.

This request can be solved with #47, #74, but in my opinion an unified inbox should display an entire inbox including subfolders from the start. Otherwise I already have the folders pane to view folders individually.

My example mailbox setup:

-INBOX  _(shown in the unified inbox view; receiving notifications)_
|-Subfolder INBOX.1 _(not shown in the unified inbox view; not receiving notifications)_
|-Subfolder INBOX.2
|-Subfolder INBOX.3
|-Subfolder INBOX.4
|-Subfolder INBOX.5

-DRAFTS
-SENT
-TRASH

-Folder 1

-Folder 2
|-Subfolder 2.1
|-Subfolder 2.2

**Comment by M66B** [comment]
Can you please check or save the account with this inbox structure and send me the debug information via 'about' after that, so I can see how the folders are exactly organized?

Which provider are you using?

**Comment by Kelvino9** [comment]
Thank you so much @M66B for fulfilling my request almost immediately.
The app is now fully functional for my use case.
To express my gratitude I just made a donation via bank transfer.

**Comment by M66B** [comment]
Thanks. Please [contact me](https://contact.faircode.eu/?product=fairemailstandalone) to have the pro features activated.
