### ISSUE TITLE
Arrow icons shaking while pulling down notification bar

### ISSUE THREAD

**Issue by ouzowtf** [M66B/open-source-email#88]
When I pull the notification bar down, the icon with the two arrows of the synchronization notification start to shake a bit after a little while and until the notification bar is fully opened and I lift my thumb.

It's a little hard to explain...

Priority for this synchronization type is set to low, but it happens with all other priorities too.

**Comment by M66B** [comment]
Android shows/manages notifications, so this seems to be a bug in your Android version.

FairEmail 'just' requests Android to show a notification.
