### ISSUE TITLE
Add option to STAR messages

### ISSUE THREAD

**Issue by licaon-kter** [M66B/open-source-email#9]
_Mark as favourite_

**Comment by M66B** [comment]
IMHO by long pressing a message

**Comment by M66B** [comment]
Star/unstar by tapping on the star in the message view.

Star/unstar in the message list is not possible yet because I don't know how yet (long press is used for read/unread already). Any ideas?

**Comment by licaon-kter** [comment]
I'd give up Archive sliding for Star sliding instead

**Comment by M66B** [comment]
Swipe is not logical because it indicates a movement in itself, so it will be a popup menu.

**Comment by licaon-kter** [comment]
I use it in other apps for STAR just fine, not sure what you mean by "logical"

**Comment by M66B** [comment]
A swipe is a movement where the entry in the list goes somewhere. In the case of FairEmail it goes to another folder. Adding/removing a star is not going somewhere but changing state.

**Comment by licaon-kter** [comment]
And I'm ok with that, just saying. 

I have swipe right for Star and left for delete, works for me :)

**Comment by rancidfrog** [comment]
Yes.
But for me I do not use neither Star nor Archive.
I would rather have anything else, an option to choose.
So, in any case there will be someone to disappoint. As there is no settings to give you options :unamused: :disappointed:
:stuck_out_tongue_winking_eye:
