### ISSUE TITLE
[FR] Improvement of the battery optimization

### ISSUE THREAD

**Issue by Primokorn** [M66B/open-source-email#90]
Hi,
You provide a how-to to disable the battery optimization from the Setup screen.
However it would be better to only ask for a "**yes**" and the app automatically disables the optimization.
I already found FLOSS apps which work like that so I'm sure it will be appreciated by your users (2s instead of 30s :smile: )

**Comment by M66B** [comment]
I would like this too, but Google will remove the app from the Play store when doing this.

"Google Play policies prohibit apps from requesting direct exemption from Power Management features in Android 6.0+ (Doze and App Standby) unless the core function of the app is adversely affected."

https://developer.android.com/training/monitoring-device-state/doze-standby#support_for_other_use_cases

There is no reasonable discussion with Google possible, so I am not going to take the risk.

**Comment by M66B** [comment]
There have been at least one XDA article about this.

**Comment by Primokorn** [comment]
Google, Google, Google... YES always means YES. Extra steps are useless.
