### ISSUE TITLE
[UI enhancement] Add another separator in the side menu

### ISSUE THREAD

**Issue by Kelvino9** [M66B/open-source-email#95]
Add another separator after standard replies in the side menu. Settings and standard replies are the only app specific menu entries that have a relevant function to the app usage. All the other entries rather serve  for information gathering.
A visual segmentation would highlight the differences of the menu entries and improves the menu structure.

About, Rate this app and other apps could also be split form the other entries, but aren't as obvious different than the above two entries.

**Comment by M66B** [comment]
Thanks for the suggestion.
