### ISSUE TITLE
Have FAQ available instead of link taking you away from app

### ISSUE THREAD

**Issue by rancidfrog** [M66B/open-source-email#96]
It is handy to have FAQ available on device and appear immediately, i.e, the following is an example of how neutriNote shows about section(similar method could show faq):
![](https://i.imgur.com/a4Gshwc.png)

This is useful as you should not really go somewhere else for useful information about app, especially when adding a popup and display it as html (since html parser/display already supported by app) is efficient and size negligible.

**Comment by M66B** [comment]
Find me a reliable, open source markdown parser and I will look into this.

The FAQ is stored as markdown file, not as HTML.

**Comment by M66B** [comment]
However, there is one disadvantage: updating the FAQ needs updating the app. This is not something I want.

**Comment by M66B** [comment]
Thanks for the suggestion anyway!

**Comment by rancidfrog** [comment]
Or have it like legend.
You can always have a link to current Latest FAQ on top with remark: Please see Latest changes -> **Link** 
But having to switch apps to see FAQ is annoying and frustrating when it can be done easily.

**Comment by rancidfrog** [comment]
A quick look|search:
- https://github.com/markdown-it/markdown-it

**Comment by rancidfrog** [comment]
Also, 
Markor app parser markdown:
https://github.com/gsantner/markor/tree/master/app/src/main/java/net/gsantner/markor/format/markdown

**Comment by M66B** [comment]
This will depend on third party libraries, which I prefer to avoid because in the end such libraries are often not maintained. Also, IMHO it is not a big deal a website is being referenced. It is not that often that you will look around in the FAQ.

**Comment by M66B** [comment]
Thanks for the suggestion anyway!

**Comment by rancidfrog** [comment]
Okay,
for me having it appear immediately like legend is better since no distractions.
Just a note, markor parses it in own classes not externally:
-  https://github.com/gsantner/markor/blob/master/app/src/main/java/net/gsantner/markor/format/markdown/MarkdownAutoFormat.java

- https://github.com/gsantner/markor/blob/master/app/src/main/java/net/gsantner/markor/format/markdown/MarkdownHighlighter.java

- https://github.com/gsantner/markor/blob/master/app/src/main/java/net/gsantner/markor/format/markdown/MarkdownHighlighterPattern.java

   
> Find me a reliable, open source markdown parser and I will look into this.
The above parses the markdown

**Comment by M66B** [comment]
It is still an external library.

**Comment by rancidfrog** [comment]
Can't you just use this?
```
/*#######################################################

*

* Maintained by Gregor Santner, 2018-

* https://gsantner.net/

*

* License: Apache 2.0 / Commercial

* https://github.com/gsantner/opoc/#licensing

* https://www.apache.org/licenses/LICENSE-2.0

*

#########################################################*/

package net.gsantner.markor.format.markdown;

import java.util.regex.Pattern;

public enum MarkdownHighlighterPattern {

BOLD(Pattern.compile("(?<=(\\n|^|\\s))(([*_]){2,3})(?=\\S)(.*?)\\S\\2(?=(\\n|$|\\s))")),

ITALICS(Pattern.compile("(?<=(\\n|^|\\s))([*_])(?=((?!\\2)|\\2{2,}))(?=\\S)(.*?)\\S\\2(?=(\\n|$|\\s))")),

HEADER(Pattern.compile("(?m)((^#{1,6}[^\\S\\n][^\\n]+)|((\\n|^)[^\\s]+.*?\\n(-{2,}|={2,})[^\\S\\n]*$))")),

LINK(Pattern.compile("\\[([^\\[]+)\\]\\(([^\\)]+)\\)")),

LIST_UNORDERED(Pattern.compile("(\\n|^)\\s{0,12}([*+-])( \\[[ xX]\\])?(?= )")),

LIST_ORDERED(Pattern.compile("(?m)^([0-9]+)(\\.)")),

QUOTATION(Pattern.compile("(\\n|^)>")),

STRIKETHROUGH(Pattern.compile("~{2}(.*?)\\S~{2}")),

CODE(Pattern.compile("(?m)(`(.*?)`)|(^[^\\S\\n]{4}.*$)")),

DOUBLESPACE_LINE_ENDING(Pattern.compile("(?m)(?<=\\S)([^\\S\\n]{2,})\\n"));

public final Pattern pattern;

MarkdownHighlighterPattern(Pattern pattern) {

this.pattern = pattern;

}

}


```

**Comment by rancidfrog** [comment]
Anyway, thank you for great work so far
