### ISSUE TITLE
Hide account name

### ISSUE THREAD

**Issue by Buxdehuda** [M66B/open-source-email#97]
Please hide the account name in the unified inbox if there is only one account used.

https://github.com/M66B/open-source-email/blob/master/app/src/main/java/eu/faircode/email/AdapterMessage.java#L137

**Comment by M66B** [comment]
Since the message adapter doesn't know about accounts, this is not trivial to change.

As a workaround you can set the account name to a space for now.

**Comment by Buxdehuda** [comment]
Can't you just set a constant on startup if account list size == 1 and use that?

Anyway, using a blank name works for me, so I'll close this issue for now.

**Comment by M66B** [comment]
The list of accounts is stored in the database. Accessing the database requires a background thread.

Also, what to do what the number of account changes.

So, not trivial.
