### ISSUE TITLE
Delete/Archive/Mark Read/Mark Unread multiple mails at once

### ISSUE THREAD

**Issue by icecoldsipra** [M66B/open-source-email#99]
# Feature request

* Did you check if there wasn't a similar feature request? Yes
* Did you read [this FAQ](https://github.com/M66B/open-source-email/blob/master/FAQ.md#FAQ15)? Yes

Currently, there is no option to delete or archive multiple emails all at once. The left/right swiping works only for one email at a time. If an optional checkbox was provided for each email in a folder, along with a global Archive or Delete button, user can easily select multiple emails and can easily delete or archive them at once saving time.

Similarly if an option to mark emails as read or mark them as unread can also help save time.

If a checkbox can be provided, then including a "Select All" option would also be quite useful.

**Comment by M66B** [comment]
IMHO this doesn't add anything because swiping a message away is less work than multiple selecting an choosing an action.

Marking read/unread is not an often used action.

Moreover, multiple selecting is often going wrong due to accidental touches.

**Comment by icecoldsipra** [comment]
Thanks for your inputs. I understand your point of view and respect it too. I personally feel swiping is more riskier as its gone instantly. But with a checkbox provided, it can help the user go back and review if the right checkboxes are marked. At least I personally do it... :)
